# Generated by Django 3.2.4 on 2021-06-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productReview', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='reviewPics')),
            ],
        ),
    ]
