# Generated by Django 3.2.4 on 2021-06-15 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
