# Generated by Django 3.2.4 on 2021-06-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientFirstName', models.CharField(max_length=255)),
                ('clientLastName', models.CharField(max_length=255)),
                ('clientEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
