# Generated by Django 3.2.4 on 2021-06-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchasedItemName',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchasedItemPrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
