# Generated by Django 3.2.4 on 2021-06-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productPrice', models.FloatField()),
                ('productName', models.CharField(max_length=255)),
                ('productDescription', models.TextField()),
            ],
        ),
    ]
