# Generated by Django 3.2.4 on 2021-06-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0002_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=255)),
                ('clientEmail', models.CharField(max_length=255)),
                ('clientMessage', models.TextField()),
            ],
        ),
    ]
