# Generated by Django 3.2.4 on 2021-06-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0003_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
