# Generated by Django 3.2.4 on 2021-06-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0004_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='awaesome',
            field=models.BooleanField(default=False),
        ),
    ]
