# Generated by Django 3.2.4 on 2021-06-15 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0006_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='UserReview',
        ),
    ]
